# Generated by Django 4.1.3 on 2022-11-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255, null=True)),
                ('stock_num', models.IntegerField(default=0, null=True)),
                ('in_stock', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
