# Generated by Django 4.1.3 on 2022-11-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='books',
            name='stock_num',
            field=models.IntegerField(default=0),
        ),
    ]
