# Generated by Django 4.1.3 on 2022-12-02 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_books_in_stock_alter_books_stock_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('auID', models.AutoField(primary_key=True, serialize=False)),
                ('au_name', models.CharField(max_length=50)),
                ('au_star', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('catID', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pID', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=50)),
                ('book_price', models.IntegerField()),
                ('book_stock', models.IntegerField()),
                ('book_star', models.FloatField()),
                ('book_description', models.CharField(max_length=254)),
                ('auID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.author')),
                ('catID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
            ],
        ),
    ]
