# Generated by Django 4.1.3 on 2022-12-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_alter_product_auid_alter_product_catid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='book_img',
            field=models.ImageField(default='uploads/default.png', upload_to='uploads/default.png'),
        ),
    ]
