# Generated by Django 4.1.3 on 2022-12-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_book_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='book_img',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
