# Generated by Django 4.1.3 on 2022-12-06 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_book_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='oID',
        ),
        migrations.RemoveField(
            model_name='product',
            name='auID',
        ),
        migrations.AddField(
            model_name='author',
            name='pID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
