# Generated by Django 4.1.3 on 2022-12-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_checkout',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ship_addr',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='book_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
