# Generated by Django 4.1.3 on 2022-12-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_invoice_date_checkout_invoice_ship_addr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='place_status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_checkout',
            field=models.DateField(null=True),
        ),
    ]
