# Generated by Django 4.1.3 on 2022-12-13 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_order_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
